spring.application.name=recycle

# DB 접속 URL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/recycleDB?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:team}
spring.datasource.password=${DB_PASSWORD}

# MySQL 드라이버 클래스 지정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis : JDBC코드보다 간결하게 쿼리 실행, 자바코드와 sql문 분리
# MyBatis 매퍼 XML 파일(쿼리 작성) 위치 지정
mybatis.mapper-locations=classpath:mapper/*.xml
# 도메인이 저장된 패키지 등록
mybatis.type-aliases-package=first_project.recycle.domain
# DB에 snake-case 저장된 컬럼명을 camel-case 자동변환
mybatis.configuration.map-underscore-to-camel-case=true
# ===== 파일 업로드 =====
spring.servlet.multipart.enabled=true
# 파일 하나 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 요청 전체(글 내용 + 파일) 최대 크기
spring.servlet.multipart.max-request-size=12MB

# 업로드된 사진이 실제로 저장되는 폴더 (프로젝트 안 upload 폴더)
# * 경로에 역슬래시(\)를 쓰면 안 됨 - properties 파일에서 특수문자라 경로가 깨짐
recycle.upload.dir=${user.dir}/upload/

# 서비스키 환경변수에서 불러오기
public-data.service-key=${PUBLIC_DATA_SERVICE_KEY}

#카카오 rest api key
kakao.rest-api-key=5089a0b1b4298cbaf48b7f964bc6d884

# 종로구 의류수거함 api 주소
public-data.jongno-clothing-bin.url=https://api.odcloud.kr/api/15104622/v1/uddi:2bbbc640-8375-4ea6-b855-e32e4de4b8c5
# 종로구 폐건전지 수거함 api 주소
public-data.jongno-battery-bin.url=https://api.odcloud.kr/api/15133679/v1/uddi:477e54a8-6425-4c85-abbb-e78d1c8bb28e